service: cas-featureflag
frameworkVersion: '3'

plugins:
  - '@nearst/serverless-dynalite'
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  timeout: 30
  environment:
    TABLE_FLAG: '${self:service}.${self:custom.stage}.flag'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
            - dynamodb:DescribeTable
          Resource: '*'

custom:
  stage: ${opt:stage, 'local'}
  webpack:
    webpackConfig: ./webpack.config.js
    excludeFiles: ./**/*.test.ts

functions:
  hooks:
    handler: ./src/application/http/hooks.handler
    events:
      - http:
          path: /hooks
          method: ANY
      - http:
          path: /hooks/{proxy+}
          method: ANY

resources:
  Resources:
    FlagTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.TABLE_FLAG}
